# Generated by Django 5.1.6 on 2025-03-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in minutes', max_digits=5),
        ),
    ]
