# Generated by Django 5.1.6 on 2025-03-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlist_app', '0004_alter_song_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setlist',
            unique_together={('song', 'set_number')},
        ),
    ]
