# Generated by Django 5.1.6 on 2025-03-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlist_app', '0005_alter_setlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
